"""Built-in CODEX color themes."""

THEMES: dict[str, dict] = {
    "dark": {
        "name": "Dark",
        "description": "Deep dark with cyan/green accents — the classic hacker terminal",
        "dark": True,
        "accent":       "#58d68d",
        "title":        "bold #58d68d",
        "subtitle":     "#8b949e",
        "muted":        "#6e7681",
        "header_rule":  "#30363d",
        "success":      "bold #3fb950",
        "warning":      "bold #d29922",
        "error":        "bold #f85149",
        "info":         "#388bfd",
        "formula":      "bold #ffa657",
        "breadcrumb":   "#8b949e",
        "menu_number":  "bold #58d68d",
        "menu_item":    "#e6edf3",
        "menu_hint":    "#6e7681",
        "menu_key":     "bold #58d68d",
        "box_fact":     "#58d68d",
        "box_note":     "#388bfd",
        "box_warning":  "#d29922",
        "box_tip":      "#bd93f9",
        "box_formula":  "#ffa657",
        "box_interactive": "#50fa7b",
        "box_art":      "#6e7681",
        "label":        "bold #58d68d",
        "value":        "#e6edf3",
        "dim":          "#6e7681",
        "progress_bar": "#58d68d",
        "progress_bg":  "#30363d",
        "tag":          "#8b949e",
        "tag_border":   "#30363d",
        "panel_border": "#30363d",
        "syntax":       "github-dark",
    },
    "dracula": {
        "name": "Dracula",
        "description": "The iconic purple & pink Dracula palette",
        "dark": True,
        "accent":       "#bd93f9",
        "title":        "bold #ff79c6",
        "subtitle":     "#6272a4",
        "muted":        "#6272a4",
        "header_rule":  "#44475a",
        "success":      "bold #50fa7b",
        "warning":      "bold #ffb86c",
        "error":        "bold #ff5555",
        "info":         "#8be9fd",
        "formula":      "bold #ffb86c",
        "breadcrumb":   "#6272a4",
        "menu_number":  "bold #bd93f9",
        "menu_item":    "#f8f8f2",
        "menu_hint":    "#6272a4",
        "menu_key":     "bold #ff79c6",
        "box_fact":     "#50fa7b",
        "box_note":     "#8be9fd",
        "box_warning":  "#ffb86c",
        "box_tip":      "#bd93f9",
        "box_formula":  "#ffb86c",
        "box_interactive": "#50fa7b",
        "box_art":      "#6272a4",
        "label":        "bold #ff79c6",
        "value":        "#f8f8f2",
        "dim":          "#6272a4",
        "progress_bar": "#bd93f9",
        "progress_bg":  "#44475a",
        "tag":          "#6272a4",
        "tag_border":   "#44475a",
        "panel_border": "#44475a",
        "syntax":       "dracula",
    },
    "nord": {
        "name": "Nord",
        "description": "Blue-grey Nordic palette — calm and focused",
        "dark": True,
        "accent":       "#88c0d0",
        "title":        "bold #88c0d0",
        "subtitle":     "#7b88a1",
        "muted":        "#616e88",
        "header_rule":  "#3b4252",
        "success":      "bold #a3be8c",
        "warning":      "bold #ebcb8b",
        "error":        "bold #bf616a",
        "info":         "#5e81ac",
        "formula":      "bold #d08770",
        "breadcrumb":   "#7b88a1",
        "menu_number":  "bold #88c0d0",
        "menu_item":    "#eceff4",
        "menu_hint":    "#616e88",
        "menu_key":     "bold #88c0d0",
        "box_fact":     "#a3be8c",
        "box_note":     "#88c0d0",
        "box_warning":  "#ebcb8b",
        "box_tip":      "#b48ead",
        "box_formula":  "#d08770",
        "box_interactive": "#a3be8c",
        "box_art":      "#616e88",
        "label":        "bold #88c0d0",
        "value":        "#eceff4",
        "dim":          "#616e88",
        "progress_bar": "#88c0d0",
        "progress_bg":  "#3b4252",
        "tag":          "#7b88a1",
        "tag_border":   "#3b4252",
        "panel_border": "#3b4252",
        "syntax":       "nord",
    },
    "monokai": {
        "name": "Monokai",
        "description": "Orange, yellow, green — the retro coder palette",
        "dark": True,
        "accent":       "#a6e22e",
        "title":        "bold #f92672",
        "subtitle":     "#75715e",
        "muted":        "#75715e",
        "header_rule":  "#3e3d32",
        "success":      "bold #a6e22e",
        "warning":      "bold #e6db74",
        "error":        "bold #f92672",
        "info":         "#66d9e8",
        "formula":      "bold #fd971f",
        "breadcrumb":   "#75715e",
        "menu_number":  "bold #a6e22e",
        "menu_item":    "#f8f8f2",
        "menu_hint":    "#75715e",
        "menu_key":     "bold #fd971f",
        "box_fact":     "#a6e22e",
        "box_note":     "#66d9e8",
        "box_warning":  "#e6db74",
        "box_tip":      "#ae81ff",
        "box_formula":  "#fd971f",
        "box_interactive": "#a6e22e",
        "box_art":      "#75715e",
        "label":        "bold #f92672",
        "value":        "#f8f8f2",
        "dim":          "#75715e",
        "progress_bar": "#a6e22e",
        "progress_bg":  "#3e3d32",
        "tag":          "#75715e",
        "tag_border":   "#3e3d32",
        "panel_border": "#3e3d32",
        "syntax":       "monokai",
    },
    "gruvbox": {
        "name": "Gruvbox",
        "description": "Earthy retro warm tones — easy on the eyes",
        "dark": True,
        "accent":       "#b8bb26",
        "title":        "bold #fb4934",
        "subtitle":     "#928374",
        "muted":        "#665c54",
        "header_rule":  "#3c3836",
        "success":      "bold #b8bb26",
        "warning":      "bold #fabd2f",
        "error":        "bold #fb4934",
        "info":         "#83a598",
        "formula":      "bold #fe8019",
        "breadcrumb":   "#928374",
        "menu_number":  "bold #b8bb26",
        "menu_item":    "#ebdbb2",
        "menu_hint":    "#665c54",
        "menu_key":     "bold #fabd2f",
        "box_fact":     "#b8bb26",
        "box_note":     "#83a598",
        "box_warning":  "#fabd2f",
        "box_tip":      "#d3869b",
        "box_formula":  "#fe8019",
        "box_interactive": "#b8bb26",
        "box_art":      "#665c54",
        "label":        "bold #fabd2f",
        "value":        "#ebdbb2",
        "dim":          "#665c54",
        "progress_bar": "#b8bb26",
        "progress_bg":  "#3c3836",
        "tag":          "#928374",
        "tag_border":   "#3c3836",
        "panel_border": "#3c3836",
        "syntax":       "gruvbox-dark",
    },
    "solarized_dark": {
        "name": "Solarized Dark",
        "description": "The classic warm dark — precision-engineered colors",
        "dark": True,
        "accent":       "#2aa198",
        "title":        "bold #268bd2",
        "subtitle":     "#586e75",
        "muted":        "#657b83",
        "header_rule":  "#073642",
        "success":      "bold #859900",
        "warning":      "bold #b58900",
        "error":        "bold #dc322f",
        "info":         "#268bd2",
        "formula":      "bold #cb4b16",
        "breadcrumb":   "#586e75",
        "menu_number":  "bold #2aa198",
        "menu_item":    "#839496",
        "menu_hint":    "#586e75",
        "menu_key":     "bold #268bd2",
        "box_fact":     "#859900",
        "box_note":     "#2aa198",
        "box_warning":  "#b58900",
        "box_tip":      "#6c71c4",
        "box_formula":  "#cb4b16",
        "box_interactive": "#859900",
        "box_art":      "#586e75",
        "label":        "bold #268bd2",
        "value":        "#839496",
        "dim":          "#586e75",
        "progress_bar": "#2aa198",
        "progress_bg":  "#073642",
        "tag":          "#586e75",
        "tag_border":   "#073642",
        "panel_border": "#073642",
        "syntax":       "solarized-dark",
    },
    "solarized_light": {
        "name": "Solarized Light",
        "description": "Warm light mode — for daytime learning sessions",
        "dark": False,
        "accent":       "#2aa198",
        "title":        "bold #268bd2",
        "subtitle":     "#657b83",
        "muted":        "#93a1a1",
        "header_rule":  "#eee8d5",
        "success":      "bold #859900",
        "warning":      "bold #b58900",
        "error":        "bold #dc322f",
        "info":         "#268bd2",
        "formula":      "bold #cb4b16",
        "breadcrumb":   "#657b83",
        "menu_number":  "bold #2aa198",
        "menu_item":    "#586e75",
        "menu_hint":    "#93a1a1",
        "menu_key":     "bold #268bd2",
        "box_fact":     "#859900",
        "box_note":     "#2aa198",
        "box_warning":  "#b58900",
        "box_tip":      "#6c71c4",
        "box_formula":  "#cb4b16",
        "box_interactive": "#859900",
        "box_art":      "#93a1a1",
        "label":        "bold #268bd2",
        "value":        "#586e75",
        "dim":          "#93a1a1",
        "progress_bar": "#2aa198",
        "progress_bg":  "#eee8d5",
        "tag":          "#657b83",
        "tag_border":   "#eee8d5",
        "panel_border": "#eee8d5",
        "syntax":       "solarized-light",
    },
    "high_contrast": {
        "name": "High Contrast",
        "description": "WCAG-compliant maximum contrast — accessibility first",
        "dark": True,
        "accent":       "#ffffff",
        "title":        "bold #ffffff",
        "subtitle":     "#cccccc",
        "muted":        "#aaaaaa",
        "header_rule":  "#444444",
        "success":      "bold #00ff00",
        "warning":      "bold #ffff00",
        "error":        "bold #ff0000",
        "info":         "#00ffff",
        "formula":      "bold #ffff00",
        "breadcrumb":   "#aaaaaa",
        "menu_number":  "bold #ffffff",
        "menu_item":    "#ffffff",
        "menu_hint":    "#aaaaaa",
        "menu_key":     "bold #00ffff",
        "box_fact":     "#00ff00",
        "box_note":     "#00ffff",
        "box_warning":  "#ffff00",
        "box_tip":      "#ff00ff",
        "box_formula":  "#ffff00",
        "box_interactive": "#00ff00",
        "box_art":      "#aaaaaa",
        "label":        "bold #ffffff",
        "value":        "#ffffff",
        "dim":          "#aaaaaa",
        "progress_bar": "#ffffff",
        "progress_bg":  "#444444",
        "tag":          "#aaaaaa",
        "tag_border":   "#444444",
        "panel_border": "#666666",
        "syntax":       "monokai",
    },
}

DEFAULT_THEME = "dark"
